import { PrismaClient } from "@prisma/client";
import { seedBusinesses } from "./businesses";

type SeedBusinesses = Awaited<ReturnType<typeof seedBusinesses>>;

export async function seedDeals(
  prisma: PrismaClient,
  businesses: SeedBusinesses,
) {
  const dealSeeds = [
    {
      id: "seed-deal-safari-family-meal",
      slug: "safari-family-meal-special",
      businessId: businesses.safariRestaurant.id,
      title: "Family Meal Special",
      description: "Enjoy 15% off family meal orders at Safari Restaurant.",
      discountText: "15% OFF",
      discountType: "percentage",
      discountValue: 15,
      promoCode: "FAMILY15",
      imageUrl: null,
      terms:
        "Valid on qualifying family meal orders. Cannot be combined with other offers.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: true,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-hodan-graduation",
      slug: "hodan-graduation-photography-special",
      businessId: businesses.hodanPhotography.id,
      title: "Graduation Photography Special",
      description: "Save 20% on select graduation photography packages.",
      discountText: "20% OFF",
      discountType: "percentage",
      discountValue: 20,
      promoCode: "GRAD20",
      imageUrl: null,
      terms:
        "Advance booking required. Offer applies to select graduation photography packages.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: true,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-barwaaqo-first-cleaning",
      slug: "barwaaqo-first-cleaning-special",
      businessId: businesses.barwaaqoCleaning.id,
      title: "First Cleaning Special",
      description:
        "New customers can save $25 on their first qualifying home cleaning service.",
      discountText: "$25 OFF",
      discountType: "fixed",
      discountValue: 25,
      promoCode: "CLEAN25",
      imageUrl: null,
      terms: "New customers only. Minimum service amount may apply.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: false,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-abdi-auto-service",
      slug: "abdi-auto-service-special",
      businessId: businesses.abdiAutoRepair.id,
      title: "Auto Service Special",
      description: "Save $20 on qualifying maintenance and repair services.",
      discountText: "$20 OFF",
      discountType: "fixed",
      discountValue: 20,
      promoCode: "AUTO20",
      imageUrl: null,
      terms:
        "Valid on qualifying services. Parts and additional fees may not be included.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: true,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-somali-tax-new-client",
      slug: "somali-tax-new-client-special",
      businessId: businesses.somaliTaxServices.id,
      title: "New Client Tax Preparation Special",
      description:
        "New clients can save $25 on qualifying individual tax preparation services.",
      discountText: "$25 OFF",
      discountType: "fixed",
      discountValue: 25,
      promoCode: "TAX25",
      imageUrl: null,
      terms: "New clients only. Valid on qualifying tax preparation services.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: true,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-zeila-web-starter",
      slug: "zeila-web-starter-package",
      businessId: businesses.zeilaWebSolutions.id,
      title: "Small Business Website Special",
      description:
        "Save 20% on select starter website packages for small businesses and entrepreneurs.",
      discountText: "20% OFF",
      discountType: "percentage",
      discountValue: 20,
      promoCode: "WEB20",
      imageUrl: null,
      terms:
        "Applies to select starter website packages. Additional development work is priced separately.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: true,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-aman-airport",
      slug: "aman-airport-ride-special",
      businessId: businesses.amanTransportation.id,
      title: "Airport Ride Special",
      description:
        "Save $10 on qualifying scheduled rides to or from MSP Airport.",
      discountText: "$10 OFF",
      discountType: "fixed",
      discountValue: 10,
      promoCode: "MSP10",
      imageUrl: null,
      terms:
        "Advance reservation required. Valid on qualifying MSP Airport rides.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: true,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-nur-home-care-consultation",
      slug: "nur-home-care-consultation",
      businessId: businesses.nurHomeCare.id,
      title: "Free Initial Consultation",
      description:
        "Schedule a complimentary initial consultation to discuss home care needs and available support.",
      discountText: "FREE CONSULTATION",
      discountType: "custom",
      discountValue: null,
      promoCode: null,
      imageUrl: null,
      terms:
        "Appointment required. Consultation does not include paid home care services.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: false,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-somali-translation",
      slug: "somali-translation-document-special",
      businessId: businesses.somaliTranslation.id,
      title: "Document Translation Special",
      description:
        "Save 15% on qualifying Somali-English document translation orders.",
      discountText: "15% OFF",
      discountType: "percentage",
      discountValue: 15,
      promoCode: "TRANSLATE15",
      imageUrl: null,
      terms:
        "Valid on qualifying document translation orders. Rush services may cost extra.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: false,
      viewsCount: 0,
      clicksCount: 0,
    },
    {
      id: "seed-deal-horn-moving",
      slug: "horn-moving-local-move-special",
      businessId: businesses.hornMoving.id,
      title: "Local Moving Special",
      description:
        "Save $50 on qualifying local moving services in the Twin Cities.",
      discountText: "$50 OFF",
      discountType: "fixed",
      discountValue: 50,
      promoCode: "MOVE50",
      imageUrl: null,
      terms:
        "Valid on qualifying local moves. Minimum booking requirements may apply.",
      startDate: new Date("2026-08-01T00:00:00.000Z"),
      validUntil: new Date("2026-12-31T23:59:59.000Z"),
      active: true,
      published: true,
      featured: false,
      viewsCount: 0,
      clicksCount: 0,
    },
  ];

  const seededDeals = [];

  for (const deal of dealSeeds) {
    const seededDeal = await prisma.deal.upsert({
      where: {
        id: deal.id,
      },
      update: {
        slug: deal.slug,
        businessId: deal.businessId,
        title: deal.title,
        description: deal.description,
        discountText: deal.discountText,
        discountType: deal.discountType,
        discountValue: deal.discountValue,
        promoCode: deal.promoCode,
        imageUrl: deal.imageUrl,
        terms: deal.terms,
        startDate: deal.startDate,
        validUntil: deal.validUntil,
        active: deal.active,
        published: deal.published,
        featured: deal.featured,
      },
      create: deal,
    });

    seededDeals.push(seededDeal);
  }

  return {
    safariFamilyMeal: seededDeals[0],
    hodanGraduation: seededDeals[1],
    barwaaqoFirstCleaning: seededDeals[2],
    abdiAutoService: seededDeals[3],
    somaliTaxNewClient: seededDeals[4],
    zeilaWebStarter: seededDeals[5],
    amanAirportRide: seededDeals[6],
    nurConsultation: seededDeals[7],
    somaliTranslationSpecial: seededDeals[8],
    hornMovingSpecial: seededDeals[9],
  };
}
