'use client';

import { ChangeEvent, FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ImagePlus } from 'lucide-react';
import AdminDashboardPage from '@/components/admin/AdminDashboardPage';
import api from '@/lib/api';
import BusinessLocationFields from '../BusinessLocationFields';

const categories=['Retail','Restaurant','Health','Education','Technology','Construction','Professional Services','Transport','Hospitality','Other'];
const initial={name:'',category:'',description:'',logoUrl:'',bannerUrl:'',website:'',phone:'',email:'',address:'',city:'',region:'',country:'Somalia',postalCode:'',latitude:'',longitude:'',weekdayHours:'',weekendHours:'',featured:false,published:true};

export default function NewBusinessPage(){
 const router=useRouter();const[form,setForm]=useState(initial);const[error,setError]=useState('');const[saving,setSaving]=useState(false);
 const set=(key:keyof typeof form,value:string|boolean)=>setForm((current)=>({...current,[key]:value}));
 const upload=async(event:ChangeEvent<HTMLInputElement>,key:'logoUrl'|'bannerUrl')=>{const file=event.target.files?.[0];if(!file)return;try{const data=new FormData();data.append('file',file);const response=await api.post('/uploads',data);set(key,response.data.url);}catch(err:any){setError(err?.response?.data?.error||'Image upload failed');}};
 const locate=()=>navigator.geolocation?.getCurrentPosition(({coords})=>{set('latitude',coords.latitude.toFixed(6));set('longitude',coords.longitude.toFixed(6));},()=>setError('Could not access this device location. You can enter coordinates manually.'));
 const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await api.post('/admin/businesses',{...form,openingHours:{weekdays:form.weekdayHours,weekends:form.weekendHours}});router.push('/admin/businesses');}catch(err:any){setError(err?.response?.data?.error||'Failed to create business');setSaving(false);}};
 const inputClass='w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/15';
 return <AdminDashboardPage title="Add business" description="Create a complete, location-aware public business listing."><form onSubmit={submit} className="mx-auto max-w-5xl space-y-6">
  {error&&<div role="alert" className="rounded-xl bg-rose-50 p-4 font-semibold text-rose-700">{error}</div>}
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Business information</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="font-bold md:col-span-2">Business name *<input required maxLength={160} value={form.name} onChange={(e)=>set('name',e.target.value)} className={`${inputClass} mt-2`}/></label><label className="font-bold">Category *<select required value={form.category} onChange={(e)=>set('category',e.target.value)} className={`${inputClass} mt-2`}><option value="">Select category</option>{categories.map((item)=><option key={item}>{item}</option>)}</select></label><label className="font-bold">Website<input type="url" value={form.website} onChange={(e)=>set('website',e.target.value)} className={`${inputClass} mt-2`}/></label><label className="font-bold md:col-span-2">Business description *<textarea required rows={5} value={form.description} onChange={(e)=>set('description',e.target.value)} className={`${inputClass} mt-2`}/></label></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Address and map location</h2><BusinessLocationFields {...form} inputClass={inputClass} onChange={(field,value)=>set(field,value)} onLocate={locate}/></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Contact, hours and images</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="font-bold">Phone<input value={form.phone} onChange={(e)=>set('phone',e.target.value)} className={`${inputClass} mt-2`}/></label><label className="font-bold">Public email<input type="email" value={form.email} onChange={(e)=>set('email',e.target.value)} className={`${inputClass} mt-2`}/></label><label className="font-bold">Weekday opening hours<input placeholder="e.g. 8:00 AM – 6:00 PM" value={form.weekdayHours} onChange={(e)=>set('weekdayHours',e.target.value)} className={`${inputClass} mt-2`}/></label><label className="font-bold">Weekend opening hours<input placeholder="e.g. 9:00 AM – 2:00 PM or Closed" value={form.weekendHours} onChange={(e)=>set('weekendHours',e.target.value)} className={`${inputClass} mt-2`}/></label><label className="cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-5 text-center font-bold"><ImagePlus className="mx-auto mb-2 text-primary"/>Upload logo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>upload(e,'logoUrl')} className="sr-only"/>{form.logoUrl&&<span className="mt-2 block text-xs text-emerald-600">Logo uploaded</span>}</label><label className="cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-5 text-center font-bold"><ImagePlus className="mx-auto mb-2 text-primary"/>Upload cover image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>upload(e,'bannerUrl')} className="sr-only"/>{form.bannerUrl&&<span className="mt-2 block text-xs text-emerald-600">Cover uploaded</span>}</label></div><div className="mt-5 flex flex-wrap gap-6"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.published} onChange={(e)=>set('published',e.target.checked)}/>Publish immediately</label><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.featured} onChange={(e)=>set('featured',e.target.checked)}/>Feature this business</label></div></section>
  <div className="flex justify-end gap-3"><button type="button" onClick={()=>router.back()} className="rounded-xl border border-slate-300 px-6 py-3 font-black">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-7 py-3 font-black text-white disabled:opacity-60">{saving?'Saving...':'Create business'}</button></div>
 </form></AdminDashboardPage>;
}
