'use client';

import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { ImagePlus } from 'lucide-react';
import AdminDashboardPage from '@/components/admin/AdminDashboardPage';
import api from '@/lib/api';
import BusinessLocationFields from '../../BusinessLocationFields';

const categories = ['Retail','Restaurant','Health','Education','Technology','Construction','Professional Services','Transport','Hospitality','Other'];
type Form = { name:string; category:string; description:string; logoUrl:string; bannerUrl:string; website:string; phone:string; email:string; address:string; city:string; region:string; country:string; postalCode:string; latitude:string; longitude:string; weekdayHours:string; weekendHours:string; featured:boolean; published:boolean };
const empty: Form = { name:'',category:'',description:'',logoUrl:'',bannerUrl:'',website:'',phone:'',email:'',address:'',city:'',region:'',country:'Somalia',postalCode:'',latitude:'',longitude:'',weekdayHours:'',weekendHours:'',featured:false,published:true };

export default function EditBusinessPage() {
  const { id } = useParams() as { id:string };
  const router = useRouter();
  const [form,setForm] = useState<Form>(empty);
  const [loading,setLoading] = useState(true);
  const [saving,setSaving] = useState(false);
  const [error,setError] = useState('');
  const set = (key:keyof Form,value:string|boolean) => setForm((current)=>({...current,[key]:value}));
  useEffect(()=>{ api.get(`/admin/businesses/${id}`).then(({data})=>{ const value=data.business; setForm({...empty,...value,latitude:value.latitude?.toString()||'',longitude:value.longitude?.toString()||'',description:value.description||'',logoUrl:value.logoUrl||'',bannerUrl:value.bannerUrl||'',website:value.website||'',phone:value.phone||'',email:value.email||'',region:value.region||'',postalCode:value.postalCode||'',weekdayHours:value.openingHours?.weekdays||'',weekendHours:value.openingHours?.weekends||''}); }).catch((err)=>setError(err?.response?.data?.error||'Failed to load business')).finally(()=>setLoading(false)); },[id]);
  const upload = async(event:ChangeEvent<HTMLInputElement>,key:'logoUrl'|'bannerUrl')=>{ const file=event.target.files?.[0]; if(!file)return; try{const data=new FormData();data.append('file',file);const response=await api.post('/uploads',data);set(key,response.data.url);}catch(err:any){setError(err?.response?.data?.error||'Image upload failed');}};
  const locate=()=>navigator.geolocation?.getCurrentPosition(({coords})=>{set('latitude',coords.latitude.toFixed(6));set('longitude',coords.longitude.toFixed(6));},()=>setError('Could not access this device location.'));
  const submit=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{await api.put(`/admin/businesses/${id}`,{...form,openingHours:{weekdays:form.weekdayHours,weekends:form.weekendHours}});router.push('/admin/businesses');}catch(err:any){setError(err?.response?.data?.error||'Failed to update business');setSaving(false);}};
  const input='mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/15';
  if(loading)return <AdminDashboardPage title="Edit business"><div className="p-12 text-center text-slate-500">Loading business...</div></AdminDashboardPage>;
  return <AdminDashboardPage title="Edit business" description="Update the public directory listing."><form onSubmit={submit} className="mx-auto max-w-5xl space-y-6">
    {error&&<div className="rounded-xl bg-rose-50 p-4 font-semibold text-rose-700">{error}</div>}
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Business information</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="font-bold md:col-span-2">Business name *<input required value={form.name} onChange={(e)=>set('name',e.target.value)} className={input}/></label><label className="font-bold">Category *<select required value={form.category} onChange={(e)=>set('category',e.target.value)} className={input}>{categories.map((x)=><option key={x}>{x}</option>)}</select></label><label className="font-bold">Website<input type="url" value={form.website} onChange={(e)=>set('website',e.target.value)} className={input}/></label><label className="font-bold md:col-span-2">Business description *<textarea required rows={5} value={form.description} onChange={(e)=>set('description',e.target.value)} className={input}/></label></div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Address and map location</h2><BusinessLocationFields {...form} inputClass={input.replace(/^mt-2 /,'')} onChange={(field,value)=>set(field,value)} onLocate={locate}/></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Contact, hours and images</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="font-bold">Phone<input value={form.phone} onChange={(e)=>set('phone',e.target.value)} className={input}/></label><label className="font-bold">Public email<input type="email" value={form.email} onChange={(e)=>set('email',e.target.value)} className={input}/></label><label className="font-bold">Weekday opening hours<input value={form.weekdayHours} onChange={(e)=>set('weekdayHours',e.target.value)} placeholder="e.g. 8:00 AM – 6:00 PM" className={input}/></label><label className="font-bold">Weekend opening hours<input value={form.weekendHours} onChange={(e)=>set('weekendHours',e.target.value)} placeholder="e.g. Closed" className={input}/></label><label className="cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-5 text-center font-bold"><ImagePlus className="mx-auto mb-2 text-primary"/>Replace logo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>upload(e,'logoUrl')} className="sr-only"/>{form.logoUrl&&<span className="mt-2 block text-xs text-emerald-600">Logo ready</span>}</label><label className="cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-5 text-center font-bold"><ImagePlus className="mx-auto mb-2 text-primary"/>Replace cover<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>upload(e,'bannerUrl')} className="sr-only"/>{form.bannerUrl&&<span className="mt-2 block text-xs text-emerald-600">Cover ready</span>}</label></div><div className="mt-5 flex gap-6"><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.published} onChange={(e)=>set('published',e.target.checked)}/>Published</label><label className="flex items-center gap-2 font-bold"><input type="checkbox" checked={form.featured} onChange={(e)=>set('featured',e.target.checked)}/>Featured</label></div></section>
    <div className="flex justify-end gap-3"><button type="button" onClick={()=>router.back()} className="rounded-xl border border-slate-300 px-6 py-3 font-black">Cancel</button><button disabled={saving} className="rounded-xl bg-blue-600 px-7 py-3 font-black text-white disabled:opacity-60">{saving?'Saving...':'Save changes'}</button></div>
  </form></AdminDashboardPage>;
}
