ALTER TABLE "services"
ADD COLUMN IF NOT EXISTS "sla_response" TEXT,
ADD COLUMN IF NOT EXISTS "attachments" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "advanced_config" JSONB NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE "courses"
ADD COLUMN IF NOT EXISTS "learning_outcomes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "requirements" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
